services:
  api:
    deploy: null
    environment:
      DATABASE_URL: mongodb://admin:admin@mongodb:27017
    image: iselabdearborn/docker-grocery-api
    ports:
    - 3000:3000
  creator:
    depends_on:
    - api
    environment:
      API_URL: http://api:3000/api
    image: iselabdearborn/docker-grocery-creator
  mongodb:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_USERNAME: admin
    image: webhippie/mongodb:latest
    ports:
    - 27017:27017
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  visualizer:
    deploy:
      placement:
        constraints:
        - node.hostname == manager
    image: dockersamples/visualizer:latest
    ports:
    - 8070:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.8'
volumes:
  data-volume:
    driver: local
